### ISSUE TITLE
Add support for restoring Pipewire session for future use (omit monitor selector dialog every time wlx-overlay starts)

### ISSUE THREAD

**Issue by oo8dev** [galister/wlx-overlay-x#10]
Related PR (OBS):
https://github.com/obsproject/obs-studio/pull/5559

**Comment by galister** [comment]
vanilla wlx already has this:

https://github.com/galister/WlxOverlay/blob/a7f2ccf433519ab7f7d8d14cbcc37487aee3e8e6/Desktop/Wayland/XdgScreenCastHandler.cs#L151-L152

https://github.com/galister/WlxOverlay/blob/a7f2ccf433519ab7f7d8d14cbcc37487aee3e8e6/Desktop/Wayland/XdgScreenCastHandler.cs#L261-L269

**Comment by oo8dev** [comment]
https://github.com/galister/wlx-overlay-x/pull/11
After I finish this PR i think we will be able to do this by creating something like `conf.d/pipewire_token.yaml`

**Comment by oo8dev** [comment]
Done in https://github.com/galister/wlx-overlay-x/pull/14
